{
 "title": "RE(D) - Request Duration Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Maximum and Minimum Durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, increase(request_duration_seconds_bucket[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0, increase(request_duration_seconds_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration Percentiles by Endpoint",
   "type": "timeseries",
   "description": "Maximum http response time experienced by x% of our users",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket[1m])) by (le, path))\r\n\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(request_duration_seconds_bucket[1m])) by (le, path))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Duration Per Minute",
   "type": "stat",
   "description": "Average Request Duration in the last minute across all APIs and instances",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_sum[1m]))/sum(rate(request_duration_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration Percentile by Endpoint and Status Code",
   "type": "timeseries",
   "description": "Maximum http response time experienced by x% of our users on endpoint x for status code XXX",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket[1m])) by (le, path, status_code))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(request_duration_seconds_bucket[1m])) by (le, path, status_code))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration Percentile by Status Code",
   "type": "timeseries",
   "description": " Maximum http response time experienced by x% of our users for status code XXX",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket[1m])) by (le, status_code))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(request_duration_seconds_bucket[1m])) by (le, status_code))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}