{
 "title": "R(E)D - Request Error Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Error Rate Percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(request_duration_seconds_count{status_code!=\"200\"}[1m]))/sum(increase(request_duration_seconds_count[1m])) *100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate Per Minute",
   "type": "timeseries",
   "description": "Ratio of the error rate over the past 1 minute to the error rate over the previous minute",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(request_duration_seconds_count{status_code!=\"200\"}[1m])/rate(request_duration_seconds_count{status_code!=\"200\"}[1m] offset 1m)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate Percentage by Endpoint ",
   "type": "timeseries",
   "description": "x% of the requests return 404 and y% return 500",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(sum(rate(request_duration_seconds_count{status_code!=\"200\"}[1m])) by (path))/(sum(rate(request_duration_seconds_count[1m])) by (path))\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}